/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teamleaguemanager.gui;

/**
 *
 * @author Fabiano
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
        mPanelViewContent.setLayout(new java.awt.BorderLayout());
        mPanelViewContent.add(new ScheduleView());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mPanelViewTitle = new javax.swing.JPanel();
        mLabelPanelViewTitle = new javax.swing.JLabel();
        mPanelViewContent = new javax.swing.JPanel();
        mMenuBar = new javax.swing.JMenuBar();
        mMenuLeagues = new javax.swing.JMenu();
        mMenuItemNewLeague = new javax.swing.JMenuItem();
        mMenuItemOpen = new javax.swing.JMenuItem();
        mMenuItemQuit = new javax.swing.JMenuItem();
        mMenuView = new javax.swing.JMenu();
        mMenuItemTeams = new javax.swing.JMenuItem();
        mMenuItemSchedule = new javax.swing.JMenuItem();
        mMenuItemRanking = new javax.swing.JMenuItem();
        mMenuHelp = new javax.swing.JMenu();
        mMenuItemGuide = new javax.swing.JMenuItem();
        mMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mPanelViewTitle.setBackground(new java.awt.Color(0, 0, 0));
        mPanelViewTitle.setForeground(new java.awt.Color(255, 255, 255));

        mLabelPanelViewTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mLabelPanelViewTitle.setForeground(new java.awt.Color(255, 255, 255));
        mLabelPanelViewTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mLabelPanelViewTitle.setText("Panel View Title");

        javax.swing.GroupLayout mPanelViewTitleLayout = new javax.swing.GroupLayout(mPanelViewTitle);
        mPanelViewTitle.setLayout(mPanelViewTitleLayout);
        mPanelViewTitleLayout.setHorizontalGroup(
            mPanelViewTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mLabelPanelViewTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        mPanelViewTitleLayout.setVerticalGroup(
            mPanelViewTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mLabelPanelViewTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        mPanelViewContent.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout mPanelViewContentLayout = new javax.swing.GroupLayout(mPanelViewContent);
        mPanelViewContent.setLayout(mPanelViewContentLayout);
        mPanelViewContentLayout.setHorizontalGroup(
            mPanelViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mPanelViewContentLayout.setVerticalGroup(
            mPanelViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        mMenuLeagues.setText("Leagues");

        mMenuItemNewLeague.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mMenuItemNewLeague.setText("New");
        mMenuLeagues.add(mMenuItemNewLeague);

        mMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mMenuItemOpen.setText("Open");
        mMenuLeagues.add(mMenuItemOpen);

        mMenuItemQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mMenuItemQuit.setText("Quit");
        mMenuLeagues.add(mMenuItemQuit);

        mMenuBar.add(mMenuLeagues);

        mMenuView.setText("View");

        mMenuItemTeams.setText("Teams");
        mMenuView.add(mMenuItemTeams);

        mMenuItemSchedule.setText("Schedule");
        mMenuView.add(mMenuItemSchedule);

        mMenuItemRanking.setText("Ranking");
        mMenuView.add(mMenuItemRanking);

        mMenuBar.add(mMenuView);

        mMenuHelp.setText("Help");

        mMenuItemGuide.setText("Guide");
        mMenuHelp.add(mMenuItemGuide);

        mMenuItemAbout.setText("About");
        mMenuHelp.add(mMenuItemAbout);

        mMenuBar.add(mMenuHelp);

        setJMenuBar(mMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanelViewTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mPanelViewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mPanelViewTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mPanelViewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mLabelPanelViewTitle;
    private javax.swing.JMenuBar mMenuBar;
    private javax.swing.JMenu mMenuHelp;
    private javax.swing.JMenuItem mMenuItemAbout;
    private javax.swing.JMenuItem mMenuItemGuide;
    private javax.swing.JMenuItem mMenuItemNewLeague;
    private javax.swing.JMenuItem mMenuItemOpen;
    private javax.swing.JMenuItem mMenuItemQuit;
    private javax.swing.JMenuItem mMenuItemRanking;
    private javax.swing.JMenuItem mMenuItemSchedule;
    private javax.swing.JMenuItem mMenuItemTeams;
    private javax.swing.JMenu mMenuLeagues;
    private javax.swing.JMenu mMenuView;
    private javax.swing.JPanel mPanelViewContent;
    private javax.swing.JPanel mPanelViewTitle;
    // End of variables declaration//GEN-END:variables
}
