/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teamleaguemanager.gui;

import java.awt.Dimension;

/**
 *
 * @author Fabiano
 */
public class MatchPanel extends javax.swing.JPanel {

    /**
     * Creates new form MatchPanel
     */
    public MatchPanel() {
        initComponents();
    }
    
    public MatchPanel(String team1, String team2) {
        initComponents();
        
        this.setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        
        this.setTeam1(team1);
        this.setTeam2(team2);
        
        mTextFieldTeam1Score.setMaximumSize(new Dimension(40, 20));
        mTextFieldTeam2Score.setMaximumSize(new Dimension(40, 20));
        
        mLabelTeam1.setMaximumSize(new Dimension(140, 20));
        mLabelTeam2.setMaximumSize(new Dimension(140, 20));
        
        mTextFieldTeam1Score.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        mTextFieldTeam2Score.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }
    
    public void setTeam1(String team1) {
        mLabelTeam1.setText(team1);
    }
    
    public void setTeam2(String team2) {
        mLabelTeam2.setText(team2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mLabelTeam1 = new javax.swing.JLabel();
        mTextFieldTeam1Score = new javax.swing.JTextField();
        mLabelVs = new javax.swing.JLabel();
        mTextFieldTeam2Score = new javax.swing.JTextField();
        mLabelTeam2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mLabelTeam1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mLabelTeam1.setText("Team 1");

        mLabelVs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mLabelVs.setText("vs");

        mLabelTeam2.setText("Team 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mLabelTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTextFieldTeam1Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mLabelVs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTextFieldTeam2Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mLabelTeam2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabelTeam1)
                    .addComponent(mTextFieldTeam1Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mLabelVs)
                    .addComponent(mTextFieldTeam2Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mLabelTeam2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mLabelTeam1;
    private javax.swing.JLabel mLabelTeam2;
    private javax.swing.JLabel mLabelVs;
    private javax.swing.JTextField mTextFieldTeam1Score;
    private javax.swing.JTextField mTextFieldTeam2Score;
    // End of variables declaration//GEN-END:variables
}
