/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teamleaguemanager.gui;

/**
 *
 * @author Fabiano
 */
public class RankingView extends javax.swing.JPanel {

    /**
     * Creates new form RankingView
     */
    public RankingView() {
        initComponents();
        
        mTableRanking.getColumn("#").setMinWidth(40);
        mTableRanking.getColumn("#").setPreferredWidth(40);
        mTableRanking.getColumn("#").setMaxWidth(40);
        
        mTableRanking.getColumn("Team").setMinWidth(270);
        mTableRanking.getColumn("Team").setPreferredWidth(270);
        mTableRanking.getColumn("Team").setMaxWidth(270);
        
        mTableRanking.getColumn("Wins").setMinWidth(60);
        mTableRanking.getColumn("Wins").setPreferredWidth(60);
        mTableRanking.getColumn("Wins").setMaxWidth(60);
        
        mTableRanking.getColumn("Losses").setMinWidth(60);
        mTableRanking.getColumn("Losses").setPreferredWidth(60);
        mTableRanking.getColumn("Losses").setMaxWidth(60);
        
        mTableRanking.getColumn("PW").setMinWidth(60);
        mTableRanking.getColumn("PW").setPreferredWidth(60);
        mTableRanking.getColumn("PW").setMaxWidth(60);
        
        mTableRanking.getColumn("PL").setMinWidth(60);
        mTableRanking.getColumn("PL").setPreferredWidth(60);
        mTableRanking.getColumn("PL").setMaxWidth(60);
        
        mTableRanking.getColumn("Diff").setMinWidth(60);
        mTableRanking.getColumn("Diff").setPreferredWidth(60);
        mTableRanking.getColumn("Diff").setMaxWidth(60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mScrollPaneRanking = new javax.swing.JScrollPane();
        mTableRanking = new javax.swing.JTable();

        mTableRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Team", "Wins", "Losses", "PW", "PL", "Diff"
            }
        ));
        mScrollPaneRanking.setViewportView(mTableRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mScrollPaneRanking, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mScrollPaneRanking, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane mScrollPaneRanking;
    private javax.swing.JTable mTableRanking;
    // End of variables declaration//GEN-END:variables
}
