/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teamleaguemanager.gui;

import javax.swing.JPanel;

/**
 *
 * @author Fabiano
 */
public class ScheduleView extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleView
     */
    public ScheduleView() {
        initComponents();
        
        JPanel matches = new JPanel();
        matches.setLayout(new javax.swing.BoxLayout(matches, javax.swing.BoxLayout.Y_AXIS));
        matches.add(new MatchPanel("SK Telecom Team 1", "KT Rolster"));
        matches.add(new MatchPanel("Samsung Khan", "CJ Entus"));
        matches.add(new MatchPanel("Hwaseung Oz", "STX Soul"));
        matches.add(new MatchPanel("MBCGame Hero", "WeMade Fox"));
        matches.add(new MatchPanel("SK Telecom Team 1", "KT Rolster"));
        matches.add(new MatchPanel("Samsung Khan", "CJ Entus"));
        matches.add(new MatchPanel("Hwaseung Oz", "STX Soul"));
        matches.add(new MatchPanel("MBCGame Hero", "WeMade Fox"));
        matches.add(new MatchPanel("SK Telecom Team 1", "KT Rolster"));
        matches.add(new MatchPanel("Samsung Khan", "CJ Entus"));
        matches.add(new MatchPanel("Hwaseung Oz", "STX Soul"));
        matches.add(new MatchPanel("MBCGame Hero", "WeMade Fox"));
        matches.add(new MatchPanel("SK Telecom Team 1", "KT Rolster"));
        matches.add(new MatchPanel("Samsung Khan", "CJ Entus"));
        matches.add(new MatchPanel("Hwaseung Oz", "STX Soul"));
        matches.add(new MatchPanel("MBCGame Hero", "WeMade Fox"));
        
        mScrollPaneMatches.getViewport().add(matches);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mLabelRound = new javax.swing.JLabel();
        mComboBoxRound = new javax.swing.JComboBox();
        mSeparator = new javax.swing.JSeparator();
        mLabelMatchDate = new javax.swing.JLabel();
        mFormattedTextFieldMatchDate = new javax.swing.JFormattedTextField();
        mLabelMatchDateExplanation = new javax.swing.JLabel();
        mScrollPaneMatches = new javax.swing.JScrollPane();
        mButtonUpdate = new javax.swing.JButton();

        mLabelRound.setText("Round");

        mComboBoxRound.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mLabelMatchDate.setText("Match Date");

        mFormattedTextFieldMatchDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));

        mLabelMatchDateExplanation.setText("(yyyy/mm/dd, ex: 2012/11/03)");

        mScrollPaneMatches.setBackground(new java.awt.Color(204, 204, 204));
        mScrollPaneMatches.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        mButtonUpdate.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mLabelRound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mComboBoxRound, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(mSeparator)
                    .addComponent(mScrollPaneMatches)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mLabelMatchDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mFormattedTextFieldMatchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mLabelMatchDateExplanation)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(mButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabelRound)
                    .addComponent(mComboBoxRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabelMatchDate)
                    .addComponent(mFormattedTextFieldMatchDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mLabelMatchDateExplanation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mScrollPaneMatches, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mButtonUpdate)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mButtonUpdate;
    private javax.swing.JComboBox mComboBoxRound;
    private javax.swing.JFormattedTextField mFormattedTextFieldMatchDate;
    private javax.swing.JLabel mLabelMatchDate;
    private javax.swing.JLabel mLabelMatchDateExplanation;
    private javax.swing.JLabel mLabelRound;
    private javax.swing.JScrollPane mScrollPaneMatches;
    private javax.swing.JSeparator mSeparator;
    // End of variables declaration//GEN-END:variables
}
