/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teamleaguemanager.gui;

/**
 *
 * @author Fabiano
 */
public class TeamView extends javax.swing.JPanel {

    /**
     * Creates new form TeamView
     */
    public TeamView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mLabelTeamName = new javax.swing.JLabel();
        mTextFieldName = new javax.swing.JTextField();
        mLabelTag = new javax.swing.JLabel();
        mTextFieldTag = new javax.swing.JTextField();
        mLabelLogo = new javax.swing.JLabel();
        mTextFieldLogo = new javax.swing.JTextField();
        mButtonChooseFile = new javax.swing.JButton();
        mLabelRoster = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mListRoster = new javax.swing.JList();
        mButtonRemovePlayer = new javax.swing.JButton();
        mButtonEditPlayer = new javax.swing.JButton();
        mButtonAddPlayer = new javax.swing.JButton();

        mLabelTeamName.setText("Name");

        mLabelTag.setText("Tag");

        mLabelLogo.setText("Logo");

        mButtonChooseFile.setText("Choose File...");

        mLabelRoster.setText("Roster");

        mListRoster.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(mListRoster);

        mButtonRemovePlayer.setText("Remove Player");

        mButtonEditPlayer.setText("Edit Player");

        mButtonAddPlayer.setText("Add Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mLabelTag)
                            .addComponent(mLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mLabelTeamName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mTextFieldName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mTextFieldLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mButtonChooseFile)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(mTextFieldTag)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mLabelRoster)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mButtonAddPlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mButtonEditPlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mButtonRemovePlayer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabelTeamName)
                    .addComponent(mTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabelTag)
                    .addComponent(mTextFieldTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabelLogo)
                    .addComponent(mTextFieldLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mButtonChooseFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mLabelRoster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButtonRemovePlayer)
                    .addComponent(mButtonEditPlayer)
                    .addComponent(mButtonAddPlayer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mButtonAddPlayer;
    private javax.swing.JButton mButtonChooseFile;
    private javax.swing.JButton mButtonEditPlayer;
    private javax.swing.JButton mButtonRemovePlayer;
    private javax.swing.JLabel mLabelLogo;
    private javax.swing.JLabel mLabelRoster;
    private javax.swing.JLabel mLabelTag;
    private javax.swing.JLabel mLabelTeamName;
    private javax.swing.JList mListRoster;
    private javax.swing.JTextField mTextFieldLogo;
    private javax.swing.JTextField mTextFieldName;
    private javax.swing.JTextField mTextFieldTag;
    // End of variables declaration//GEN-END:variables
}
